name: Browser Utils
on:
  push:
    branches:
      - master

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node Version
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: 'true'
        run: npm run test

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node Version
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: 'true'
        run: npm run test

  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Node Version
        uses: actions/setup-node@master
        with:
          node-version: '10.x'

      - name: Install
        run: yarn

      - name: Test
        env:
          CI: 'true'
        run: npm run test:cov

      - name: Coverage
        run: npx codecov

  build-and-deploy:
    needs: [test-ubuntu, test-macOS, test-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: yarn && npm run build
